# Generated by Django 4.0.2 on 2022-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('donor_username', models.CharField(max_length=200)),
                ('donor_email', models.CharField(max_length=200)),
                ('donor_password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
    ]
